apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-http
  labels:
    app: simple-http
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-http
  template:
    metadata:
      labels:
        app: simple-http
    spec:
      containers:
      - name: simple-http
        image: simple-http
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: simple-http
spec:
  type: ClusterIP
  selector:
      app: simple-http
  ports:
    - port: 5000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: simple-http
              port:
                number: 5000
